security:
  basic:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp
    username: postgres
    password: pg123456
<<<<<<< HEAD
  messages:
    basename: message/messages

flyway:
  enabled: true
=======

flyway:
  enabled: false
>>>>>>> dev_branch
  clean-disabled: true
  baseline-on-migrate: true
  baseline-version: 0
  locations:
    - classpath:db/migration

mybatis:
  type-aliases-package: com.kingland.bootcamp.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
<<<<<<< HEAD
  port: 8888
  application:
     name:bootcamp

=======
  port: 8888
>>>>>>> dev_branch
